-- =====================================================================
--  QUINIELA MUNDIAL 2026 — Setup de base de datos (Supabase / Postgres)
--  Cómo usarlo:
--    1. Entra a tu proyecto en supabase.com
--    2. Menú izquierdo -> SQL Editor -> New query
--    3. Pega TODO este archivo y dale "Run"
--  Crea 3 tablas + seguridad. No guarda contraseñas en texto plano
--  (la app manda solo un hash SHA-256).
-- =====================================================================

-- ---------- PARTICIPANTES ----------
create table if not exists participantes (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  nombre_key  text not null unique,         -- nombre en minúsculas (clave de login)
  pass_hash   text not null,
  creado      timestamptz not null default now()
);

-- ---------- PRONOSTICOS ----------
create table if not exists pronosticos (
  id          bigint generated by default as identity primary key,
  nombre_key  text not null,
  nombre      text not null,
  match_id    int  not null,
  gl          int  not null,                -- goles local
  gv          int  not null,                -- goles visitante
  fase        text not null,
  locked      boolean not null default false,
  actualizado timestamptz not null default now(),
  unique (nombre_key, match_id)
);

-- ---------- ESTADO (resultados, fases abiertas, equipos override) ----------
-- Una sola fila (id=1) con un JSON que controla el admin.
create table if not exists estado (
  id    int primary key default 1,
  data  jsonb not null default '{"results":{},"open":{},"teams":{}}'::jsonb
);
insert into estado (id, data)
  values (1, '{"results":{},"open":{},"teams":{}}'::jsonb)
  on conflict (id) do nothing;

-- =====================================================================
--  SEGURIDAD (Row Level Security)
--  Quiniela entre conocidos: lectura pública, escritura permitida pero
--  con una regla clave -> un pronóstico BLOQUEADO ya no se puede cambiar.
-- =====================================================================
alter table participantes enable row level security;
alter table pronosticos  enable row level security;
alter table estado       enable row level security;

-- participantes: cualquiera puede registrarse y leer (para login)
drop policy if exists p_part_sel on participantes;
drop policy if exists p_part_ins on participantes;
create policy p_part_sel on participantes for select using (true);
create policy p_part_ins on participantes for insert with check (true);

-- pronosticos: lectura pública; insertar libre;
-- actualizar SOLO si la fila previa NO estaba bloqueada (anti-trampa)
drop policy if exists p_pred_sel on pronosticos;
drop policy if exists p_pred_ins on pronosticos;
drop policy if exists p_pred_upd on pronosticos;
create policy p_pred_sel on pronosticos for select using (true);
create policy p_pred_ins on pronosticos for insert with check (true);
create policy p_pred_upd on pronosticos for update using (locked = false);

-- estado: lectura pública; escritura libre (la protege la clave de admin en la app)
drop policy if exists p_est_sel on estado;
drop policy if exists p_est_all on estado;
create policy p_est_sel on estado for select using (true);
create policy p_est_all on estado for all using (true) with check (true);

-- Listo. Vuelve a la app, pega Project URL + anon key en config.js y a jugar.
